spring:
  datasource:
    #url: jdbc:h2:file:./db/botDbjdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true


